### ISSUE TITLE
Installation instructions and compatibility with gazebo

### ISSUE THREAD

**Issue by prajval10** [shadow-robot/sr_ur_arm#69]
- Could you please provide install instructions for this library? The instructions here : https://shadow-robot.readthedocs.io/en/latest/index.html are deprecated and the one here: https://dexterous-hand.readthedocs.io/en/latest/user_guide/1_3_setting_up_a_simulated_hand.html#gazebo does not seem to contain the **UR10+shadow hand simulation**.

- I would like to know if the `melodic-devel` branch supports UR10+shadow hand simulation in Gazebo `v9.0` and ROS Melodic as again the instructions in the README are presented for older versions.  

Cheers,
Prajval

**Comment by prajval10** [comment]
The instructions present in https://shadow-robot.readthedocs.io/en/latest/generated/sr_interface/sr_robot_launch/README.html meant for Kinetic and Indigo works also in Melodic.

**Comment by toliver** [comment]
Hi @prajval10. We are currently migrating to the new [UR ROS driver](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver ) that is supported by the manufacturer.

Some of the advantages it has over this one are:
- It can gracefully recover from protective or emergency stop (whereas this driver will crash in such circumstances)
- It uses the internal calibration of the arm, which allows it to achieve the end effector position accuracy specified by the manufacturer.
- It is compatible with the e series (UR10e etc)

So we will mark this repository as deprecated.

**Comment by prajval10** [comment]
Hi @toliver, thanks for the response. In any case, I needed a simulation for the shadow hand + UR10 which is working even in Melodic. Looking forward to the new repo 👍
