### ISSUE TITLE
Migrate to new firmware version

### ISSUE THREAD

**Issue by ugocupcic** [shadow-robot/sr_ur_arm#9]

**Comment by toliver** [comment]
It seems that there is a problem with the latest firmware version of UR. People in the ROS industrial driver are experiencing the same issues, and they recommend to downgrade until UR solves the problem.

https://github.com/ros-industrial/universal_robot/issues/183

**Comment by fmessmer** [comment]
see my [comment](https://github.com/ros-industrial/universal_robot/issues/199#issuecomment-105941460)

**Comment by toliver** [comment]
Thank you @ipa-fxm . We will try to test the new FW as soon as it is released (provided that we have an arm available at that time).

**Comment by toliver** [comment]
This [branch](https://github.com/shadow-robot/sr_ur_arm/tree/F%239_adapt_to_v3.2) has been tested with v3.2 on a UR5.

The protocol been updated as in the link included in https://github.com/ros-industrial/universal_robot/issues/183#issuecomment-158635524.

Before merging the mentioned branch we need to make it compatible with both v3.0-v3.1 and v3.2. It should be an easy fix.
